name: Publish npm package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - run: pnpm build
      - run: cp package.json dist
      - run: cp README.md dist
      - run: cp LICENSE dist
      - run: pnpm config set "//registry.npmjs.org/:_authToken=${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}
      - run: pnpm publish --access public --no-git-checks
